version: '3.8'
services:
  oloapi:
    image: docker.institut4000.gmbh/olo/oloapi
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 3001:3001
    depends_on:
      - "postgresdb"

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432 
