version: '3.8'
services:
  olo:
    image: oloapi
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 3000:3000
    depends_on:
      - "postgresdb"

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432 
